
services:
  stats-server:
    container_name: ewm-stats-server
    build: ewm-stats-service/stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_HOST=stats-db
      - DB_PORT=5432
      - DB_NAME=ewm-statistics
      - DB_USER=postgres
      - DB_PASSWORD=iamroot

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-statistics
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  ewm-service:
    container_name: ewm-main-service
    build: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://localhost:9090
      - DB_HOST=ewm-main-db
      - DB_PORT=5432
      - DB_NAME=ewm-main-service
      - DB_USER=postgres
      - DB_PASSWORD=iamroot

  ewm-db:
   image: postgres:14-alpine
   container_name: ewm-main-db
   ports:
     - "6542:5432"
   environment:
     - POSTGRES_DB=ewm-main
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=iamroot